kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rsyslog
  labels:
    app:  rsyslog-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: "ibmc-file-bronze"
